// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// State machine driving the `sigstore-tuf` verification workflow over an external HTTP client.
final class SigstoreTufUpdater implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  SigstoreTufUpdater._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _sigstore_SigstoreTufUpdater_destroy_mv1(this, _ffi.cast());
    }
  }

  // ignore: experimental_member_use
  @meta.RecordUse()
  // ignore: non_constant_identifier_names
  static void _sigstore_SigstoreTufUpdater_destroy_mv1(SigstoreTufUpdater cl, ffi.Pointer<ffi.Void> pointer) => _finalizer.attach(cl, pointer);

  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_internal_sigstore_SigstoreTufUpdater_destroy_mv1));

  /// Creates a new TUF refresh state machine for `tuf_mirror_url` and `cache_dir`.
  ///
  /// Throws [SigstoreError] on failure.
  static SigstoreTufUpdater create(String tufMirrorUrl, String cacheDir) {
    ensureBoringInitialized();
    final temp = _FinalizedArena();
    final result = _sigstore_SigstoreTufUpdater_create_mv1(tufMirrorUrl._utf8AllocIn(temp.arena), cacheDir._utf8AllocIn(temp.arena));
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return SigstoreTufUpdater._fromFfi(result.union.ok, []);
  }

  /// Advances the TUF state machine until it either completes (writing an empty string)
  /// or requests an HTTP GET (writing the pending URL to `write`).
  ///
  /// Throws [SigstoreError] on failure.
  String poll() {
    final write = _Write();
    final result = _sigstore_SigstoreTufUpdater_poll_mv1(_ffi, write._ffi);
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return write.finalize();
  }

  /// Returns the maximum allowed response size in bytes for the currently pending HTTP GET.
  int maxResponseBytes() {
    final result = _sigstore_SigstoreTufUpdater_max_response_bytes_mv1(_ffi);
    return result;
  }

  /// Supplies the HTTP status code and response body for the currently pending HTTP GET.
  void provideResponse(int statusCode, core.List<int> body) {
    final temp = _FinalizedArena();
    _sigstore_SigstoreTufUpdater_provide_response_mv1(_ffi, statusCode, body._uint8AllocIn(temp.arena));
  }

  /// Supplies a transport error for the currently pending HTTP GET.
  void provideError(String message) {
    final temp = _FinalizedArena();
    _sigstore_SigstoreTufUpdater_provide_error_mv1(_ffi, message._utf8AllocIn(temp.arena));
  }

  /// Writes the verified `trusted_root.json` string after `poll` returns `true`.
  ///
  /// Throws [SigstoreError] on failure.
  String takeResult() {
    final write = _Write();
    final result = _sigstore_SigstoreTufUpdater_take_result_mv1(_ffi, write._ffi);
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return write.finalize();
  }

}

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'sigstore_SigstoreTufUpdater_destroy_mv1')
// ignore: non_constant_identifier_names
external void _internal_sigstore_SigstoreTufUpdater_destroy_mv1(ffi.Pointer<ffi.Void> self);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultOpaqueInt32 Function(_SliceUtf8, _SliceUtf8)>(isLeaf: true, symbol: 'sigstore_SigstoreTufUpdater_create_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _sigstore_SigstoreTufUpdater_create_mv1(_SliceUtf8 tufMirrorUrl, _SliceUtf8 cacheDir);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultVoidInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreTufUpdater_poll_mv1')
// ignore: non_constant_identifier_names
external _ResultVoidInt32 _sigstore_SigstoreTufUpdater_poll_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> write);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreTufUpdater_max_response_bytes_mv1')
// ignore: non_constant_identifier_names
external int _sigstore_SigstoreTufUpdater_max_response_bytes_mv1(ffi.Pointer<ffi.Opaque> self);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>, ffi.Uint16, _SliceUint8)>(isLeaf: true, symbol: 'sigstore_SigstoreTufUpdater_provide_response_mv1')
// ignore: non_constant_identifier_names
external void _sigstore_SigstoreTufUpdater_provide_response_mv1(ffi.Pointer<ffi.Opaque> self, int statusCode, _SliceUint8 body);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Opaque>, _SliceUtf8)>(isLeaf: true, symbol: 'sigstore_SigstoreTufUpdater_provide_error_mv1')
// ignore: non_constant_identifier_names
external void _sigstore_SigstoreTufUpdater_provide_error_mv1(ffi.Pointer<ffi.Opaque> self, _SliceUtf8 message);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultVoidInt32 Function(ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreTufUpdater_take_result_mv1')
// ignore: non_constant_identifier_names
external _ResultVoidInt32 _sigstore_SigstoreTufUpdater_take_result_mv1(ffi.Pointer<ffi.Opaque> self, ffi.Pointer<ffi.Opaque> write);

// dart format on
