// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

enum SigstoreError {
  // ignore: public_member_api_docs
  invalidBundle,
  // ignore: public_member_api_docs
  verificationFailed,
  // ignore: public_member_api_docs
  signingFailed,
  // ignore: public_member_api_docs
  oidcError,
  // ignore: public_member_api_docs
  networkError,
  // ignore: public_member_api_docs
  internalError;

}

// dart format on
