// generated by diplomat-tool
// dart format off

part of 'lib.g.dart';

/// Internal FFI entry point for initializing BoringSSL symbols and verifying Sigstore bundles.
final class SigstoreVerifier implements ffi.Finalizable {
  final ffi.Pointer<ffi.Opaque> _ffi;

  // These are "used" in the sense that they keep dependencies alive
  // ignore: unused_field
  final core.List<Object> _selfEdge;

  // This takes in a list of lifetime edges (including for &self borrows)
  // corresponding to data this may borrow from. These should be flat arrays containing
  // references to objects, and this object will hold on to them to keep them alive and
  // maintain borrow validity.
  SigstoreVerifier._fromFfi(this._ffi, this._selfEdge) {
    if (_selfEdge.isEmpty) {
      _sigstore_SigstoreVerifier_destroy_mv1(this, _ffi.cast());
    }
  }

  // ignore: experimental_member_use
  @meta.RecordUse()
  // ignore: non_constant_identifier_names
  static void _sigstore_SigstoreVerifier_destroy_mv1(SigstoreVerifier cl, ffi.Pointer<ffi.Void> pointer) => _finalizer.attach(cl, pointer);

  static final _finalizer = ffi.NativeFinalizer(ffi.Native.addressOf(_internal_sigstore_SigstoreVerifier_destroy_mv1));

  /// Initializes the BoringSSL function pointer table from `package:boring` (`libbssl_dart`).
  ///
  /// `symbol_addrs` must contain the exact 28 function pointers defined by `BoringSymbols`.
  ///
  /// Throws [SigstoreError] on failure.
  static void initBoring(core.List<int> symbolAddrs) {
    final temp = _FinalizedArena();
    final result = _sigstore_SigstoreVerifier_init_boring_mv1(symbolAddrs._usizeAllocIn(temp.arena));
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
  }

  /// Verifies an artifact against a Sigstore bundle and verification policy.
  ///
  /// - `artifact_bytes`: Raw artifact bytes, or precomputed SHA-256 digest bytes if `is_digest` is true.
  /// - `is_digest`: Set to `true` if `artifact_bytes` contains the precomputed SHA-256 digest (32 bytes).
  /// - `bundle`: The parsed bundle containing signatures and verification material.
  /// - `policy`: The verification policy specifying expected identity, issuer, and trusted root.
  ///
  /// Throws [SigstoreError] on failure.
  static SigstoreVerificationResult verify(core.List<int> artifactBytes, bool isDigest, SigstoreBundle bundle, SigstoreVerificationPolicy policy) {
    final temp = _FinalizedArena();
    final result = _sigstore_SigstoreVerifier_verify_mv1(artifactBytes._uint8AllocIn(temp.arena), isDigest, bundle._ffi, policy._ffi);
    if (!result.isOk) {
      throw SigstoreError.values[result.union.err];
    }
    return SigstoreVerificationResult._fromFfi(result.union.ok, []);
  }

}

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(isLeaf: true, symbol: 'sigstore_SigstoreVerifier_destroy_mv1')
// ignore: non_constant_identifier_names
external void _internal_sigstore_SigstoreVerifier_destroy_mv1(ffi.Pointer<ffi.Void> self);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultVoidInt32 Function(_SliceUsize)>(isLeaf: true, symbol: 'sigstore_SigstoreVerifier_init_boring_mv1')
// ignore: non_constant_identifier_names
external _ResultVoidInt32 _sigstore_SigstoreVerifier_init_boring_mv1(_SliceUsize symbolAddrs);

// ignore: experimental_member_use
@meta.RecordUse()
@ffi.Native<_ResultOpaqueInt32 Function(_SliceUint8, ffi.Bool, ffi.Pointer<ffi.Opaque>, ffi.Pointer<ffi.Opaque>)>(isLeaf: true, symbol: 'sigstore_SigstoreVerifier_verify_mv1')
// ignore: non_constant_identifier_names
external _ResultOpaqueInt32 _sigstore_SigstoreVerifier_verify_mv1(_SliceUint8 artifactBytes, bool isDigest, ffi.Pointer<ffi.Opaque> bundle, ffi.Pointer<ffi.Opaque> policy);

// dart format on
