[package]
name = "aws-lc-rs"
version = "1.18.0"
edition = "2021"
description = "BoringSSL (package:boring) shim for aws-lc-rs used by sigstore-dart"
license = "BSD-3-Clause"

[features]
default = ["alloc"]
alloc = []
ring-io = []
ring-sig-verify = []
unstable = []
fips = []
non-fips = []
asan = []
bindgen = []
prebuilt-nasm = []
test_logging = []
dev-tests-only = []
aws-lc-sys = []
