// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// ignore_for_file: public_member_api_docs

// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN
//
//    dart tool/regenerate_hashes.dart <github tag>
//

const version = 'binaries-v0.1.1';

const fileHashes = <(String, String), String>{
  ('x86_64-unknown-linux-gnu', 'dynamic'):
      'c472f1c29cbae190b8de971aa84831cadc7cb50fdb2eb2a94cffe5606853ffed',
  ('x86_64-unknown-linux-gnu', 'static'):
      '5c51372e43027567a576eb3e6fbcad265279c0b525b548fd166c6a1e74e99cef',
  ('aarch64-apple-darwin', 'dynamic'):
      '96e9e7e804766dca4d43b60ea074b05e190badc34fd7feb8a733100696117724',
  ('aarch64-apple-darwin', 'static'):
      '8c64a58cea707e6ebd18d16e5b159e69cb644c80ca0f723b68f72afbcc3505b1',
  ('x86_64-pc-windows-msvc', 'dynamic'):
      '2ff1733beb1ff1fa20cfa82b0480b80e53a3d5b02a051e46b259de038f5ce463',
  ('x86_64-pc-windows-msvc', 'static'):
      'f3d1bc4992e1f42cdbba699ad67928513440a9668baecb29ec20d6a3865dc0b5',
};
