// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// ignore_for_file: public_member_api_docs

// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN
//
//    dart tool/regenerate_hashes.dart <github tag>
//

const version = 'binaries-v0.1.2';

const fileHashes = <(String, String), String>{
  ('x86_64-unknown-linux-gnu', 'dynamic'):
      '06145ad64849c62d1c88e1a965b8c007906fc2b10cc9d4cbbbb822b359864441',
  ('x86_64-unknown-linux-gnu', 'static'):
      '4ab67005bc2e8502c9eef5f935ff672e02fe38a1e2e2e78f0e11d3674dc707c7',
  ('aarch64-apple-darwin', 'dynamic'):
      '440ba7a9b715de1642b2fb3d82537bec4949417f6167463f4ca1c6a2376cdc30',
  ('aarch64-apple-darwin', 'static'):
      '2254d98876df29fdec7c1e8a24e1c8ac8aba9d56877d5656ab2c68d280258cd4',
  ('x86_64-pc-windows-msvc', 'dynamic'):
      'da45ad2e0cf45b0e0c71c1bc5bf44ff2c56018b087fd440aee7cf1fc0ca959ed',
  ('x86_64-pc-windows-msvc', 'static'):
      '34d2a9df00a645ee073ddbe78c2326f1b9ee06ed7938195bd3aa31af30c7cf2a',
};
